### ISSUE TITLE
Failed to activate the markdown-table-editor package

### ISSUE THREAD

**Issue by SniperJebus** [susisu/atom-markdown-table-editor#24]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-table-editor](https://github.com/susisu/atom-markdown-table-editor) package 1.1.2

### Stack Trace

Failed to activate the markdown-table-editor package

```
At Cannot find module '../modules/web.dom.iterable'

Error: Cannot find module '../modules/web.dom.iterable'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-table-editor/node_modules/core-js/library/fn/get-iterator.js:1:156)
    at /packages/markdown-table-editor/node_modules/core-js/library/fn/get-iterator.js:5:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-table-editor/node_modules/babel-runtime/core-js/get-iterator.js:1:186)
    at /packages/markdown-table-editor/node_modules/babel-runtime/core-js/get-iterator.js:2:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-table-editor/node_modules/babel-core/lib/transformation/file/index.js:6:21)
    at /packages/markdown-table-editor/node_modules/babel-core/lib/transformation/file/index.js:706:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
language-markdown 0.25.1 
markdown-table-editor 1.1.2 
```

**Comment by susisu** [comment]
It seems that the module has not been installed correctly.
Try reinstall atom-markdown-table-editor, and does it still occur?
